import type { Program } from "../../types";
import type { ExecutionResult } from "./runtime";
import { Runtime } from "./runtime";
import { StackRuntime } from "../algorithms/stack";
import { QueueRuntime } from "../algorithms/queue";
import { BSTRuntime } from "../algorithms/bst";
import { RBTreeRuntime } from "../algorithms/rbtree";
import { GraphRuntime } from "../algorithms/dijkstra";
import { QuickSortRuntime } from "../algorithms/quicksort";
import { HeapSortRuntime } from "../algorithms/heapsort";
import { AVLTreeRuntime } from "../algorithms/avl";
import { MergeSortRuntime } from "../algorithms/mergesort";
import { BubbleSortRuntime } from "../algorithms/bubblesort";
import { InsertionSortRuntime } from "../algorithms/insertionsort";
import { BinarySearchRuntime } from "../algorithms/binarysearch";
import { HuffmanTreeRuntime } from "../algorithms/huffman";
import { KMPRuntime } from "../algorithms/kmp";
import { HashTableRuntime } from "../algorithms/hashtable";
import { SelectionSortRuntime } from "../algorithms/selectionsort";
import { ShellSortRuntime } from "../algorithms/shellsort";
import { NaiveStringMatchingRuntime } from "../algorithms/naivestr";
import { UnionFindRuntime } from "../algorithms/unionfind";
import { ActivitySelectionRuntime } from "../algorithms/activityselection";
import { CountingSortRuntime } from "../algorithms/countingsort";
import { RadixSortRuntime } from "../algorithms/radixsort";
import { BTreeRuntime } from "../algorithms/btree";
import { BPlusTreeRuntime } from "../algorithms/bplustree";
import { TrieRuntime } from "../algorithms/trie";
import { KnapsackRuntime } from "../algorithms/knapsack";
import { LCSRuntime } from "../algorithms/lcs";
import { EditDistanceRuntime } from "../algorithms/editdistance";
import { MatrixChainRuntime } from "../algorithms/matrixchain";
import { LISRuntime } from "../algorithms/lis";
import { SplayTreeRuntime } from "../algorithms/splaytree";
import { TwoThreeTreeRuntime } from "../algorithms/twothreetree";
import { SkipListRuntime } from "../algorithms/skiplist";
import { FractionalKnapsackRuntime } from "../algorithms/fractionalknapsack";
import { JobSchedulingRuntime } from "../algorithms/jobscheduling";
import { BucketSortRuntime } from "../algorithms/bucketsort";
import { StringHashRuntime } from "../algorithms/stringhash";
import { ProcessSchedulerRuntime } from "../algorithms/processScheduling";
import { PageReplacerRuntime } from "../algorithms/pageReplacement";
import { BankerRuntime } from "../algorithms/banker";
import { MemoryAllocatorRuntime } from "../algorithms/memoryAllocation";
import { DiskSchedulerRuntime } from "../algorithms/diskScheduling";
import { ProducerConsumerRuntime } from "../algorithms/producerConsumer";
import { CRCRuntime } from "../algorithms/crc";
import { SlidingWindowRuntime } from "../algorithms/slidingWindow";
import { SubnettingRuntime } from "../algorithms/subnetting";
import { DistanceVectorRuntime } from "../algorithms/distanceVector";
import { TCPStateMachineRuntime } from "../algorithms/tcpStateMachine";
import { TwosComplementRuntime } from "../algorithms/twosComplement";
import { IEEE754Runtime } from "../algorithms/ieee754";
import { BoothMultiplyRuntime } from "../algorithms/booth";
import { CacheMappingRuntime } from "../algorithms/cacheMapping";
import { PipelineRuntime } from "../algorithms/pipeline";
import { PrioritySchedulerRuntime } from "../algorithms/priorityScheduling";
import { ClockReplacementRuntime } from "../algorithms/clockReplacement";
import { CScanDiskRuntime } from "../algorithms/cscanDisk";
import { ReadersWritersRuntime } from "../algorithms/readersWriters";
import { DiningPhilosophersRuntime } from "../algorithms/diningPhilosophers";
import { DeadlockDetectionRuntime } from "../algorithms/deadlockDetection";
import { PagingRuntime } from "../algorithms/paging";
import { UFCompressRuntime } from "../algorithms/ufCompress";
import { BinaryHeapRuntime } from "../algorithms/binaryHeap";
import { HuffmanDecodeRuntime } from "../algorithms/huffmanDecode";
import { FloatArithmeticRuntime } from "../algorithms/floatArithmetic";
import { CacheFullyAssocRuntime } from "../algorithms/cacheFullyAssoc";
import { VirtualAddressRuntime } from "../algorithms/virtualAddress";
import { SignMagnitudeMulRuntime } from "../algorithms/signMagnitudeMul";
import { PipelineSuperscalarRuntime } from "../algorithms/pipelineSuperscalar";
import { HammingRuntime } from "../algorithms/hamming";
import { CSMARuntime } from "../algorithms/csma";
import { LinkStateRuntime } from "../algorithms/linkState";
import { NATRuntime } from "../algorithms/nat";
import { TCPCongestionRuntime } from "../algorithms/tcpCongestion";

export function createRuntime(): { execute(program: Program): ExecutionResult } {
  const runtime = new Runtime();

  runtime.registerClass("Stack", () => new StackRuntime());
  runtime.registerClass("Queue", () => new QueueRuntime());
  runtime.registerClass("BST", () => new BSTRuntime());
  runtime.registerClass("RBTree", () => new RBTreeRuntime());
  runtime.registerClass("AVLTree", () => new AVLTreeRuntime());
  runtime.registerClass("Huffman", () => new HuffmanTreeRuntime());
  runtime.registerClass("Graph", (args) => {
    const nodeCount = Number(args[0] ?? 0);
    return new GraphRuntime(nodeCount);
  });
  runtime.registerClass("QuickSort", () => new QuickSortRuntime());
  runtime.registerClass("HeapSort", () => new HeapSortRuntime());
  runtime.registerClass("MergeSort", () => new MergeSortRuntime());
  runtime.registerClass("BubbleSort", () => new BubbleSortRuntime());
  runtime.registerClass("InsertionSort", () => new InsertionSortRuntime());
  runtime.registerClass("BinarySearch", () => new BinarySearchRuntime());
  runtime.registerClass("KMP", () => new KMPRuntime());
  runtime.registerClass("HashTable", (args) => {
    const size = Number(args[0] ?? 13);
    const mode = String(args[1] ?? "linear") as "linear" | "chain";
    return new HashTableRuntime(size, mode);
  });
  runtime.registerClass("SelectionSort", () => new SelectionSortRuntime());
  runtime.registerClass("ShellSort", () => new ShellSortRuntime());
  runtime.registerClass("NaiveStr", () => new NaiveStringMatchingRuntime());
  runtime.registerClass("UnionFind", () => new UnionFindRuntime());
  runtime.registerClass("ActivitySelection", () => new ActivitySelectionRuntime());
  runtime.registerClass("CountingSort", () => new CountingSortRuntime());
  runtime.registerClass("RadixSort", () => new RadixSortRuntime());
  runtime.registerClass("BTree", (args) => new BTreeRuntime(Number(args[0] ?? 3)));
  runtime.registerClass("BPlusTree", (args) => new BPlusTreeRuntime(Number(args[0] ?? 3)));
  runtime.registerClass("Trie", () => new TrieRuntime());
  runtime.registerClass("Knapsack", () => new KnapsackRuntime());
  runtime.registerClass("LCS", () => new LCSRuntime());
  runtime.registerClass("EditDistance", () => new EditDistanceRuntime());
  runtime.registerClass("MatrixChain", () => new MatrixChainRuntime());
  runtime.registerClass("LIS", () => new LISRuntime());
  runtime.registerClass("SplayTree", () => new SplayTreeRuntime());
  runtime.registerClass("TwoThreeTree", () => new TwoThreeTreeRuntime());
  runtime.registerClass("SkipList", () => new SkipListRuntime());
  runtime.registerClass("FractionalKnapsack", () => new FractionalKnapsackRuntime());
  runtime.registerClass("JobScheduling", () => new JobSchedulingRuntime());
  runtime.registerClass("BucketSort", () => new BucketSortRuntime());
  runtime.registerClass("StringHash", () => new StringHashRuntime());
  runtime.registerClass("ProcessScheduler", () => new ProcessSchedulerRuntime());
  runtime.registerClass("PageReplacer", () => new PageReplacerRuntime());
  runtime.registerClass("Banker", () => new BankerRuntime());
  runtime.registerClass("MemoryAllocator", () => new MemoryAllocatorRuntime());
  runtime.registerClass("DiskScheduler", () => new DiskSchedulerRuntime());
  runtime.registerClass("ProducerConsumer", () => new ProducerConsumerRuntime());
  runtime.registerClass("CRC", () => new CRCRuntime());
  runtime.registerClass("SlidingWindow", () => new SlidingWindowRuntime());
  runtime.registerClass("Subnetting", () => new SubnettingRuntime());
  runtime.registerClass("DistanceVector", () => new DistanceVectorRuntime());
  runtime.registerClass("TCPStateMachine", () => new TCPStateMachineRuntime());
  runtime.registerClass("TwosComplement", () => new TwosComplementRuntime());
  runtime.registerClass("IEEE754", () => new IEEE754Runtime());
  runtime.registerClass("BoothMultiply", () => new BoothMultiplyRuntime());
  runtime.registerClass("CacheMapping", () => new CacheMappingRuntime());
  runtime.registerClass("Pipeline", () => new PipelineRuntime());
  runtime.registerClass("PriorityScheduler", () => new PrioritySchedulerRuntime());
  runtime.registerClass("ClockReplacement", () => new ClockReplacementRuntime());
  runtime.registerClass("CScanDisk", () => new CScanDiskRuntime());
  runtime.registerClass("ReadersWriters", () => new ReadersWritersRuntime());
  runtime.registerClass("DiningPhilosophers", () => new DiningPhilosophersRuntime());
  runtime.registerClass("DeadlockDetection", () => new DeadlockDetectionRuntime());
  runtime.registerClass("Paging", () => new PagingRuntime());
  runtime.registerClass("UFCompress", () => new UFCompressRuntime());
  runtime.registerClass("BinaryHeap", () => new BinaryHeapRuntime());
  runtime.registerClass("HuffmanDecode", () => new HuffmanDecodeRuntime());
  runtime.registerClass("FloatArithmetic", () => new FloatArithmeticRuntime());
  runtime.registerClass("CacheFullyAssoc", () => new CacheFullyAssocRuntime());
  runtime.registerClass("VirtualAddress", () => new VirtualAddressRuntime());
  runtime.registerClass("SignMagnitudeMul", () => new SignMagnitudeMulRuntime());
  runtime.registerClass("PipelineSuperscalar", () => new PipelineSuperscalarRuntime());
  runtime.registerClass("Hamming", () => new HammingRuntime());
  runtime.registerClass("CSMA", () => new CSMARuntime());
  runtime.registerClass("LinkState", () => new LinkStateRuntime());
  runtime.registerClass("NAT", () => new NATRuntime());
  runtime.registerClass("TCPCongestion", () => new TCPCongestionRuntime());

  return {
    execute(program: Program): ExecutionResult {
      return runtime.execute(program);
    },
  };
}

export { Runtime } from "./runtime";
export { TraceRecorder } from "./traceRecorder";
